### ISSUE TITLE
Python 3.11?

### ISSUE THREAD

**Issue by jimmymathews** [nadeemlab/cg-gnn#7]
Is there anything holding this package back from support for Python 3.11, the most recent release?

**Comment by CarlinLiao** [comment]
The histocartography packages cggnn depends on assume the older Python version specified in the environment yaml.

Not strictly related to this, but squidpy appears to prefer 3.9 as well.

**Comment by CarlinLiao** [comment]
FYI type hints that don't require imports from the typing package like `Optional` or `Union` were added in python 3.11 only. Not having to import the capitalized `List` for hints was added in 3.9.

**Comment by CarlinLiao** [comment]
After pulling in the latest changes in [histocartography](https://github.com/BiomedSciAI/histocartography) and testing, I think I can remove the python 3.9 requirement pending a few further updates on my part.

These changes can be accelerated if [SPT#185](https://github.com/nadeemlab/SPT/pull/185) is completed in a speedy fashion.

**Comment by CarlinLiao** [comment]
Latest change bumps required version to 3.11. Almost certainly more strict than it needs to be, but we've been developing exclusively on 3.11 anyway.
